"use client";
import {useId,useRef,useState} from "react";
import Markdown from "react-markdown";
import remarkGfm from "remark-gfm";
import {remarkUnderline} from "@/lib/remark-underline";
import {messageParts,formResponse,type MessageForm,type MessageAction,type FormValues} from "@/lib/message-ui";
export function MessageMarkdown({text}:{text:string}){
 return <div className="min-w-0 break-words [&_p]:my-2 [&_p]:whitespace-pre-wrap [&_p:first-child]:mt-0 [&_p:last-child]:mb-0 [&_strong]:font-semibold [&_em]:italic [&_u]:underline [&_ul]:my-2 [&_ul]:list-disc [&_ul]:pl-5 [&_ol]:my-2 [&_ol]:list-decimal [&_ol]:pl-5 [&_li]:my-1 [&_blockquote]:my-2 [&_blockquote]:border-l-2 [&_blockquote]:border-wa-accent [&_blockquote]:pl-3 [&_h1]:my-2 [&_h1]:text-lg [&_h1]:font-semibold [&_h2]:my-2 [&_h2]:font-semibold [&_h3]:my-2 [&_h3]:font-semibold [&_pre]:my-2 [&_pre]:overflow-x-auto [&_pre]:rounded-lg [&_pre]:bg-black/5 [&_pre]:p-3 [&_code]:whitespace-pre-wrap [&_code]:font-mono [&_code]:text-[13px] [&_hr]:my-3 [&_hr]:border-wa-border"><Markdown skipHtml remarkPlugins={[remarkGfm,remarkUnderline]} components={{a:({href,children})=>href?<a href={href} target="_blank" rel="noopener noreferrer" className="text-wa-accent underline">{children}</a>:<span>{children}</span>,img:({alt})=><span className="text-wa-muted">{alt||"Image"}</span>,table:({children})=><div className="my-2 max-w-full overflow-x-auto"><table className="border-collapse text-sm [&_td]:border [&_td]:border-wa-border [&_td]:p-2 [&_th]:border [&_th]:border-wa-border [&_th]:p-2">{children}</table></div>}}>{text}</Markdown></div>;
}
export function MessageContent({text,disabled,answered,answerText,onRespond}:{text:string;disabled:boolean;answered:boolean;answerText?:string;onRespond:(text:string)=>Promise<unknown>}){
 return <>{messageParts(text).map((part,index)=>"text" in part?<MessageMarkdown key={index} text={part.text}/>:<ChatForm key={index} form={part.form} disabled={disabled} answered={answered} answerText={answerText} onRespond={onRespond}/>)}</>;
}
function ChatForm({form,disabled,answered,answerText,onRespond}:{form:MessageForm;disabled:boolean;answered:boolean;answerText?:string;onRespond:(text:string)=>Promise<unknown>}){
 const prefix=useId();const element=useRef<HTMLFormElement>(null);const [values,setValues]=useState<FormValues>({});const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const fieldClass="w-full min-w-0 rounded-lg border border-wa-border bg-wa-panel px-3 py-2 text-sm outline-none focus:border-wa-green";
 async function submit(action:MessageAction){if(busy||disabled||answered||!element.current?.reportValidity())return;setError("");try{const text=formResponse(form,values,action);setBusy(true);await onRespond(text);}catch(e){setError(e instanceof Error?e.message:"Could not send your response.");}finally{setBusy(false);}}
 return <form ref={element} onSubmit={e=>{e.preventDefault();const selected=(e.nativeEvent as SubmitEvent).submitter?.getAttribute("value");void submit(form.actions.find(action=>action.id===selected)||form.actions[0]);}} className="my-3 min-w-[200px] space-y-3 rounded-xl border border-wa-border p-3"><p className="font-semibold">{form.title}</p>{answered?<p className="whitespace-pre-wrap text-sm">{answerText||"Response sent in this chat."}</p>:<fieldset disabled={busy||disabled} className="space-y-3 disabled:opacity-60">{form.fields.map(field=>{
 const inputID=`${prefix}-${field.id}`;const update=(value:string|boolean|string[])=>setValues(old=>({...old,[field.id]:value}));
 if(field.type==="radio"||field.type==="checkboxes")return <fieldset key={field.id} className="space-y-2"><legend className="mb-1 text-sm font-medium">{field.label}{field.required?" *":""}</legend>{field.options.map(option=><label key={option.value} className="flex cursor-pointer items-center gap-2 text-sm"><input type={field.type==="radio"?"radio":"checkbox"} name={inputID} value={option.value} required={field.type==="radio"&&field.required} checked={field.type==="radio"?values[field.id]===option.value:Array.isArray(values[field.id])&&(values[field.id] as string[]).includes(option.value)} onChange={e=>field.type==="radio"?update(option.value):update(e.target.checked?[...(Array.isArray(values[field.id])?values[field.id] as string[]:[]),option.value]:(Array.isArray(values[field.id])?values[field.id] as string[]:[]).filter(v=>v!==option.value))} className="accent-wa-green"/>{option.label}</label>)}</fieldset>;
 if(field.type==="checkbox")return <label key={field.id} className="flex items-center gap-2 text-sm"><input type="checkbox" required={field.required} checked={values[field.id]===true} onChange={e=>update(e.target.checked)} className="accent-wa-green"/>{field.label}</label>;
 return <div key={field.id} className="space-y-1"><label htmlFor={inputID} className="text-sm font-medium">{field.label}{field.required?" *":""}</label>{field.type==="select"?<select id={inputID} required={field.required} value={typeof values[field.id]==="string"?values[field.id] as string:""} onChange={e=>update(e.target.value)} className={fieldClass}><option value="">Choose an option</option>{field.options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>:field.type==="textarea"?<textarea id={inputID} required={field.required} rows={3} maxLength={4000} placeholder={field.placeholder} value={typeof values[field.id]==="string"?values[field.id] as string:""} onChange={e=>update(e.target.value)} className={fieldClass}/>:<input id={inputID} type={field.type} required={field.required} maxLength={4000} placeholder={field.placeholder} value={typeof values[field.id]==="string"?values[field.id] as string:""} onChange={e=>update(e.target.value)} className={fieldClass}/>}</div>;
 })}<div className="flex flex-wrap gap-2">{form.actions.map((action,index)=><button key={action.id} type="submit" value={action.id} className={`rounded-full px-4 py-2 text-sm ${index===0?"bg-wa-green text-black":"border border-wa-border hover:bg-wa-hover"}`}>{action.label}</button>)}</div></fieldset>}{answered&&<p role="status" className="text-xs text-wa-muted">Response sent in this chat.</p>}{error&&<p role="alert" className="text-xs text-red-500">{error}</p>}<p className="text-[11px] text-wa-muted">Sends your response to this bot.</p></form>;
}
