"use client";
import {useEffect,useState} from "react";
import {X} from "lucide-react";
import {listSchedules,previewSchedule,saveSchedule,controlSchedule} from "@/app/actions/bots";
import type {Computer} from "@/lib/bots";
import type {BotSchedule,ScheduleInput,ScheduleState} from "@/lib/schedules";
const blank:ScheduleInput={title:"",prompt:"",mode:"ai",computer_id:null,kind:"cron",cron:"0 9 * * *",timezone:"UTC",run_at:null};
const field="w-full rounded-xl border border-wa-border bg-wa-input px-3 py-2 text-sm outline-none focus:border-wa-green";
const button="rounded-full border border-wa-border px-3 py-2 text-sm hover:bg-wa-hover disabled:opacity-40";
function localDate(value:string|null){if(!value)return "";const date=new Date(value);if(!Number.isFinite(date.getTime()))return "";return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function dateLabel(value:string,zone:string){try{return new Date(value).toLocaleString(undefined,{timeZone:zone,dateStyle:"medium",timeStyle:"short"});}catch{return value;}}
export function SchedulePanel({botID,computers,initial,onClose}:{botID:number;computers:Computer[];initial?:ScheduleInput;onClose:()=>void}){
 const [state,setState]=useState<ScheduleState|null>(null);const [editing,setEditing]=useState<number|null>(null);const [draft,setDraft]=useState<ScheduleInput>(initial||blank);const [showForm,setShowForm]=useState(!!initial);const [zone,setZone]=useState("UTC");const [dates,setDates]=useState<string[]>([]);const [previewed,setPreviewed]=useState("");const [approved,setApproved]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{let active=true;const timer=setInterval(refresh,5000);const start=setTimeout(()=>{const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone;setZone(timezone);if(!initial)setDraft({...blank,timezone});void refresh();},0);async function refresh(){const r=await listSchedules(botID);if(active){if(r.data)setState(r.data);else setError(r.error);}}return()=>{active=false;clearTimeout(start);clearInterval(timer);};},[botID,initial]);
 async function reload(){const r=await listSchedules(botID);if(r.data)setState(r.data);else setError(r.error);}
 function change(next:Partial<ScheduleInput>){setDraft(d=>({...d,...next}));setDates([]);setPreviewed("");setApproved(false);}
 function edit(job?:BotSchedule){setEditing(job?.id||null);setDraft(job?{title:job.title,prompt:job.prompt,mode:job.mode,computer_id:job.computer_id,kind:job.kind,cron:job.cron,timezone:job.timezone,run_at:job.run_at}:{...blank,timezone:zone});setShowForm(true);setDates([]);setPreviewed("");setApproved(false);setError("");}
 async function act(id:number,action:"pause"|"resume"|"run"|"delete"){setBusy(true);setError("");try{const r=await controlSchedule(botID,id,action);if(r.error)setError(r.error);await reload();}finally{setBusy(false);}}
 async function preview(){setBusy(true);setError("");try{const r=await previewSchedule(botID,draft);if(r.data){setDates(r.data);setPreviewed(JSON.stringify(draft));}else setError(r.error);}finally{setBusy(false);}}
 async function save(e:React.FormEvent){e.preventDefault();if(previewed!==JSON.stringify(draft))return;setBusy(true);setError("");try{const r=await saveSchedule(botID,draft,approved,editing||undefined);if(r.error)setError(r.error);else{setShowForm(false);setEditing(null);await reload();}}finally{setBusy(false);}}
 return <section aria-label="Bot schedules" className="flex h-full flex-col bg-wa-panel"><header className="flex h-16 shrink-0 items-center gap-3 border-b border-wa-border px-3 sm:px-4"><button aria-label="Back to chat" onClick={onClose} className="flex h-10 w-10 items-center justify-center rounded-full hover:bg-wa-hover"><X size={22}/></button><h2 className="text-[16px]">Tasks & schedules</h2></header><div className="wa-scroll min-h-0 flex-1 overflow-y-auto p-5"><p className="mb-4 text-sm text-wa-muted">Run once at a date and time, or repeat with cron. Results appear in this bot’s chat even when your browser is closed. The Blew server must stay running.</p>
 {state&&!state.worker_configured&&<p role="alert" className="mb-3 text-sm text-red-500">The scheduler is not configured on this server. Ask the server administrator to configure SCHEDULER_SECRET.</p>}
 {error&&<p role="alert" className="mb-3 text-sm text-red-500">{error}</p>}
 {!showForm?<button onClick={()=>edit()} className="mb-4 rounded-full bg-wa-green px-4 py-2 text-black">New scheduled task</button>:<form onSubmit={save} className="mb-5 space-y-3 rounded-2xl border border-wa-border p-4">
 <h3 className="font-medium">{editing?"Edit task":"Schedule task"}</h3>
 <label className="block space-y-1 text-sm"><span>Title</span><input required maxLength={160} className={field} value={draft.title} onChange={e=>change({title:e.target.value})}/></label>
 <label className="block space-y-1 text-sm"><span>Task type</span><select className={field} value={draft.mode} onChange={e=>change({mode:e.target.value as ScheduleInput["mode"]})}><option value="ai">Ask this bot</option><option value="command">Run an approved Linux command</option></select></label>
 <label className="block space-y-1 text-sm"><span>{draft.mode==="ai"?"Instructions for the bot":"Exact command to run"}</span><textarea required rows={4} maxLength={16000} className={field} value={draft.prompt} onChange={e=>change({prompt:e.target.value})}/></label>
 {draft.mode==="command"&&<label className="block space-y-1 text-sm"><span>Linux computer</span><select required className={field} value={draft.computer_id||""} onChange={e=>change({computer_id:Number(e.target.value)||null})}><option value="">Choose your computer</option>{computers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
 <label className="block space-y-1 text-sm"><span>When</span><select className={field} value={draft.kind} onChange={e=>change({kind:e.target.value as ScheduleInput["kind"],timezone:zone})}><option value="once">Once — date and time</option><option value="cron">Recurring — cron</option></select></label>
 {draft.kind==="once"?<label className="block space-y-1 text-sm"><span>Date and time ({zone})</span><input required type="datetime-local" className={field} value={localDate(draft.run_at)} onChange={e=>{const d=new Date(e.target.value);change({run_at:Number.isFinite(d.getTime())?d.toISOString():null,timezone:zone});}}/></label>:<><label className="block space-y-1 text-sm"><span>Cron expression</span><input required className={field} value={draft.cron} onChange={e=>change({cron:e.target.value})}/></label><div className="flex flex-wrap gap-2">{[["Daily 9am","0 9 * * *"],["Weekdays 9am","0 9 * * 1-5"],["Hourly","0 * * * *"],["Monthly","0 9 1 * *"]].map(([label,cron])=><button key={cron} type="button" className={button} onClick={()=>change({cron})}>{label}</button>)}</div><p className="text-xs text-wa-muted">minute hour day-of-month month weekday. Standard five-field cron; no seconds, L, W or # extensions.</p><label className="block space-y-1 text-sm"><span>Timezone</span><input required className={field} value={draft.timezone} placeholder="Asia/Kolkata" onChange={e=>change({timezone:e.target.value})}/></label></>}
 <button type="button" disabled={busy} onClick={()=>void preview()} className={button}>Preview next dates</button>
 {!!dates.length&&<div className="rounded-lg bg-wa-input p-3 text-sm"><p className="mb-2 font-medium">Next runs · {draft.timezone}</p>{dates.map(date=><p key={date}>{dateLabel(date,draft.timezone)}</p>)}</div>}
 {draft.mode==="command"?<label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/><span>I approve this exact command to run automatically at these times with my Linux user’s permissions.</span></label>:<p className="text-xs text-wa-muted">Uses your account’s selected Engine and its usage allowance. Any new Linux command the bot proposes will still need approval in chat.</p>}
 <div className="flex gap-2"><button disabled={busy||previewed!==JSON.stringify(draft)||(draft.mode==="command"&&!approved)} className="rounded-full bg-wa-green px-4 py-2 text-black disabled:opacity-40">{busy?"Saving…":editing?"Save changes":"Enable schedule"}</button><button type="button" onClick={()=>setShowForm(false)} className={button}>Cancel</button></div>
 </form>}
 <div className="space-y-3">{state?.schedules.map(job=><article key={job.id} className="space-y-2 rounded-xl border border-wa-border p-4"><p className="font-medium">{job.title} <span className="text-xs text-wa-muted">· {job.enabled?"Enabled":"Paused / finished"}</span></p><p className="text-xs text-wa-muted">{job.mode==="ai"?"AI task":"Linux command"} · {job.kind==="cron"?`${job.cron} · ${job.timezone}`:"One-time"}</p><p className="text-sm">{job.next_run?`Next: ${dateLabel(job.next_run,job.timezone)} (${job.timezone})`:"No further runs"}</p><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>edit(job)}>Edit</button><button className={button} disabled={busy} onClick={()=>void act(job.id,job.enabled?"pause":"resume")}>{job.enabled?"Pause & stop":"Resume"}</button><button className={button} disabled={busy} onClick={()=>void act(job.id,"run")}>Run now</button><button className={button} disabled={busy} onClick={()=>void act(job.id,"delete")}>Remove</button></div></article>)}</div>
 <h3 className="mb-3 mt-6 font-medium">Recent runs</h3>{!state?.runs.length&&<p className="text-sm text-wa-muted">No runs yet.</p>}{state?.runs.map(run=><div key={run.id} className="mb-3 rounded-xl bg-wa-input p-3 text-sm"><p>{run.title} · {run.status}</p><p className="text-xs text-wa-muted">{new Date(run.started_at).toLocaleString()}</p>{run.error&&<p className="mt-1 text-red-500">{run.error}</p>}</div>)}
 <p className="mt-5 text-xs leading-relaxed text-wa-muted">Schedules do not overlap for the same bot. After downtime, one missed run up to 12 hours old can run; older occurrences are marked missed. Failed runs are not automatically retried. The Linux companion must be online when a command is due.</p>
 </div></section>;
}
