import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import {memoryContext} from '../src/lib/bot-memory.ts';
import {attachmentContent} from '../src/lib/attachment-content.ts';
import {botInstructions,extractTask} from '../src/lib/bots.ts';
function setup({user={id:19,name:'Pat',email:'pat@example.test'},selected={provider:'codex',model:'test'},fail=false,file=null}={}){
 const seen={engine:[],calls:[]};const conversation={bot:{id:3,name:'Alex',designation:'Engineer',instructions:'Stay brief'},turns:[{id:'old-turn',status:'complete',user_text:'Hi',assistant_text:'Hello'}]};
 if(file)conversation.turns.push({id:"request-1234567890",status:"pending",user_text:"Read this",assistant_text:"",attachments:[file]});
 const api=async(path,options)=>{seen.calls.push({path,options});if(path.includes('/memory?'))return {memories:[],total:0,pending:0,semantic:false};if(path.endsWith('/turns'))return {started:true,attempt:'nonce'};if(path==='/api/profile')return {name:'Pat',about:'I prefer explanations'};if(path==='/api/computers'||path.endsWith('/tasks'))return [];if(path==='/api/bots/3')return conversation;};
 const modules={'./bot-memory':{memoryContext},'./attachment-content':{attachmentContent},'./api':{api},'./auth':{getCurrentUser:async()=>user},'./session':{getSessionToken:async()=>'session19'},'./engine/store':{readConfig:async id=>{assert.equal(id,19);return {selected};},withEngineLock:async(id,fn)=>{assert.equal(id,19);return fn();}},'./engine/generate':{generateReply:async(...args)=>{seen.engine.push(args);if(fail)throw Error('upstream secret detail');return 'Hello Pat, I am Alex.';}},'./bots':{botInstructions,extractTask}};
 const {outputText}=ts.transpileModule(readFileSync(new URL('../src/lib/bot-reply.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}});const exports={};vm.runInNewContext(outputText,{exports,Buffer,Error,AbortSignal,process:{env:{}},fetch:async(url,options)=>{assert.match(url,/api\/bots\/3\/attachments\//);assert.equal(options.headers.Authorization,"Bearer session19");return {ok:true,arrayBuffer:async()=>Buffer.from("Private file content")};},require:name=>modules[name]});return {respond:exports.respondToBot,seen};
}
test('generation uses current account credentials and profile with persisted bot identity',async()=>{const {respond,seen}=setup();await respond(3,'request-1234567890','Help me');const [owner,prompt,messages]=seen.engine[0];assert.equal(owner,19);assert.match(prompt,/Pat/);assert.match(prompt,/Alex/);assert.match(prompt,/I prefer explanations/);assert.equal(messages.at(-1).content,'Help me');assert(seen.calls.every(c=>c.options.token==='session19'));assert.equal(seen.calls.find(c=>c.path.endsWith('/finish')).options.json.text,'Hello Pat, I am Alex.');});
test('missing login and missing engine prevent generation',async()=>{for(const option of [{user:null},{selected:null}]){const {respond,seen}=setup(option);await assert.rejects(respond(3,'request-1234567890','Hello'));assert.equal(seen.engine.length,0);assert(!seen.calls.some(c=>c.path.endsWith('/turns')));}});
test('provider failure saves retryable state without exposing raw provider errors',async()=>{const {respond,seen}=setup({fail:true});await respond(3,'request-1234567890','Hello');const result=seen.calls.find(c=>c.path.endsWith('/finish')).options.json;assert.match(result.error,/Check Engine/);assert(!result.error.includes('secret'));assert.equal(result.attempt,'nonce');});

test('owned attachment contents and Linux references reach the selected account engine',async()=>{const file={id:'a'.repeat(48),name:'notes.txt',media_type:'text/plain',size:20};const {respond,seen}=setup({file});await respond(3,'request-1234567890','Read this',undefined,false,[file.id]);const content=seen.engine[0][2].at(-1).content;assert.match(content,/Private file content/);assert.match(content,/BLEW_FILE_aaaa/);assert.match(content,/untrusted/);assert.deepEqual(seen.calls.find(c=>c.path.endsWith('/turns')).options.json.attachments,[file.id]);});
test('invalid attachment references are rejected before starting a turn',async()=>{const {respond,seen}=setup();await assert.rejects(respond(3,'request-1234567890','Read this',undefined,false,['../other-account']));assert.equal(seen.calls.length,0);assert.equal(seen.engine.length,0);});
